global using Project.API.Helpers;
global using Project.BLL.AuthService;
global using Project.DAL.Entities;
global using Microsoft.AspNetCore.Identity.UI.Services;
global using Microsoft.AspNetCore.Http;
global using Microsoft.AspNetCore.Mvc;
global using Microsoft.AspNetCore.Identity.Data;
global using Project.API.APIAbstraction;
global using Project.BLL.Contracts;
global using RegisterRequest = Project.BLL.Contracts.RegisterRequest;
global using ResendConfirmationEmailRequest = Project.BLL.Contracts.ResendConfirmationEmailRequest;
global using ResetPasswordRequest = Project.BLL.Contracts.ResetPasswordRequest;
global using Microsoft.AspNetCore.Identity;
global using Microsoft.EntityFrameworkCore;
global using Project.API.Services;
global using Project.BLL.Mapping;
global using Project.BLL.Authantication;
global using Project.DAL.Persistence;
global using Microsoft.Extensions.Configuration;
global using System.Net;
global using System.Net.Mail;
global using System.Threading.Tasks;
global using LoginRequest = Project.BLL.Contracts.LoginRequest;
global using Microsoft.AspNetCore.Authentication.JwtBearer;
global using Microsoft.IdentityModel.Tokens;
global using System.Text;
global using Project.BLL.IServices;
global using Project.DAL.IRepository;
global using Project.DAL.Repository;
global using Microsoft.AspNetCore.Authorization;
global using System.Security.Claims;
global using Project.BLL.DTOS;

